version: 2
image: ubuntu:16.04
jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          - dependencies-

      - run: |
          yarn
          yarn lint
          yarn build
          yarn test

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}

