version: 2
image: ubuntu:16.04
jobs:
  build:
    docker:
      - image: node:9.8.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          - dependencies-

      - run:
          name: Installing dependencies
          command: yarn

      - run:
          name: Linting source files
          command: yarn lint

      - run:
          name: Building production bundle
          command: yarn build

      - run:
          name: Running tests
          command: yarn test

      - run:
          name: Building and uploading storybook for visual diff
          working_directory: ~/repo
          command: |
            scripts/fetch-skin.sh
            yarn percy; true

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}

