version: 2
image: ubuntu:16.04
jobs:
  build:
    docker:
      - image: node:9.8.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          - dependencies-

      - run: |
          yarn
          yarn lint
          yarn build
          yarn test
          yarn percy; true

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}

