name: Build, Test, Lint and Sonar

on:
  push:
    branches:
      - 'master'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_and_tests:
    name: Build, Lint and Test
    runs-on: ubuntu-latest
    steps:
    -
      name: Project checkout
      uses: actions/checkout@v3
    -
      name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 12
    -
      name: Setup browser
      uses: browser-actions/setup-chrome@latest
    -
      name: Execute browser
      run: chrome --version
    -
      name: Install dependencies
      run: yarn
    -
      name: Run linter
      run: yarn lint
    -
      name: Build production bundle
      run: yarn build
    -
      name: Run Tests
      run: yarn test-coverage
    -
      name: Upload Coverage
      uses: actions/upload-artifact@v3
      with:
        name: former-kit-coverage
        path: coverage/
        retention-days: 1
    -
      name: Build styleguidist
      run: yarn styleguide:build
    -
      name: Build and upload storybook for visual diff
      run: |
        scripts/fetch-skin.sh
        yarn percy; true

  sonar:
    name: Sonar
    needs: lint_and_tests
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    -
      name: Download coverage
      uses: actions/download-artifact@v2
      with:
        name: former-kit-coverage
        path: coverage/
    -
      name: Rename source from coverage file
      run: sed -i 's/\/home\/runner\/work\/former-kit\/former-kit\///g' coverage/lcov.info
    -
      name: Run Sonar
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
